// let date= new Date(1)
// console.log(date.toString())
// console.log(date.toLocaleString())
// console.log(date.toDateString())
// let d= Date.now(1000)
// console.log(d/1000)

let date= new Date("2024 09 2")
console.log(date)
console.log(date.toString())
console.log(date.getUTCDate())
console.log(date.setDate("6").toString())